/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Entidad.ClsProducto;
import Negocio.ClsNegProducto;
import Presentacion.Principal;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class PnlAgrearProducto extends javax.swing.JPanel {

     ClsNegProducto obnegproducto;
    ClsProducto objproducto;
    public PnlAgrearProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnshdRegistrar = new rscomponentshade.RSButtonShade();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcantidad = new rscomponentshade.RSTextFieldShade();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtprecio = new rscomponentshade.RSTextFieldShade();
        txtcodigo = new rscomponentshade.RSTextFieldShade();
        txtdescripcion = new rscomponentshade.RSTextFieldShade();
        btnshdCancelar = new rscomponentshade.RSButtonShade();

        setLayout(null);

        btnshdRegistrar.setBackground(new java.awt.Color(0, 51, 102));
        btnshdRegistrar.setText("Registrar");
        btnshdRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshdRegistrarActionPerformed(evt);
            }
        });
        add(btnshdRegistrar);
        btnshdRegistrar.setBounds(70, 430, 200, 45);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PRODUCTO");
        add(jLabel1);
        jLabel1.setBounds(0, 40, 374, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad");
        add(jLabel4);
        jLabel4.setBounds(350, 190, 66, 19);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo");
        add(jLabel2);
        jLabel2.setBounds(40, 120, 51, 19);

        txtcantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcantidad.setPlaceholder("Ingrese cantidad");
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        add(txtcantidad);
        txtcantidad.setBounds(460, 180, 207, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Precio");
        add(jLabel6);
        jLabel6.setBounds(42, 188, 48, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descripcion");
        add(jLabel3);
        jLabel3.setBounds(340, 120, 88, 19);

        txtprecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprecio.setPlaceholder("Ingrese precio");
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });
        add(txtprecio);
        txtprecio.setBounds(100, 183, 230, 30);

        txtcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigo.setPlaceholder("Ingrese codigo");
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        add(txtcodigo);
        txtcodigo.setBounds(110, 120, 200, 30);

        txtdescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdescripcion.setPlaceholder("Ingrese Descripicon");
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });
        add(txtdescripcion);
        txtdescripcion.setBounds(460, 120, 409, 30);

        btnshdCancelar.setBackground(new java.awt.Color(0, 51, 102));
        btnshdCancelar.setText("Cancelar");
        btnshdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshdCancelarActionPerformed(evt);
            }
        });
        add(btnshdCancelar);
        btnshdCancelar.setBounds(660, 440, 200, 45);
    }// </editor-fold>//GEN-END:initComponents

    private void btnshdRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshdRegistrarActionPerformed
        // haces aqui validaciones WE

        String codigo=txtcodigo.getText().toString();
        String descripcion=txtdescripcion.getText().toString();
        int cantidad=Integer.parseInt(txtcantidad.getText().toString());
        double precio= Double.parseDouble( txtprecio.getText().toString());

        Registrar(codigo,descripcion,cantidad,precio);
    }//GEN-LAST:event_btnshdRegistrarActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        //        char validar =evt.getKeyChar();
        //        if (Character.isLetter(validar)) {
            //            getToolkit().beep();
            //            evt.consume();
            //            JOptionPane.showMessageDialog(null, "Solo Numeros", "No", 1);
            //
            //        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
        // TODO add your handling code here:

        char validar=evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Letras", "No", 1);
        }
    }//GEN-LAST:event_txtdescripcionKeyTyped
private void Registrar(String codigo, String descripcion, int cantidad, double precio) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    obnegproducto = new ClsNegProducto();
     if (obnegproducto.Existe(codigo)) {
         JOptionPane.showMessageDialog(null, "ya Existe esete codigo", "No", 1);
         return;
     }
     
      objproducto = new ClsProducto();
      objproducto.setIdproducto(codigo);    
     objproducto.setDescripcion(descripcion);
     objproducto.setPrecio(precio);
     objproducto.setCantidad(cantidad);
     obnegproducto.Registar(objproducto);     
     JOptionPane.showMessageDialog(null, "Registado We", "Yes", 1);
              
 }
    private void btnshdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshdCancelarActionPerformed
        new ClsCambiarPanel(Principal.pnlPrincipalPaneles, new Paneles.PnlProductos());
        Principal.lblInicio.setText("Gestión producotos");
    }//GEN-LAST:event_btnshdCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnshdCancelar;
    private rscomponentshade.RSButtonShade btnshdRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private rscomponentshade.RSTextFieldShade txtcantidad;
    private rscomponentshade.RSTextFieldShade txtcodigo;
    private rscomponentshade.RSTextFieldShade txtdescripcion;
    private rscomponentshade.RSTextFieldShade txtprecio;
    // End of variables declaration//GEN-END:variables

  
}
